# Generated by Django 5.0.2 on 2024-02-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largeproject',
            name='date_created',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
