# Generated by Django 5.0.2 on 2024-02-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_essaydocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EssayDocument',
            new_name='Document',
        ),
    ]
