# Generated by Django 5.0.2 on 2024-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_essaydocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', to='base.document'),
        ),
    ]
