# Generated by Django 5.0.2 on 2024-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subproject_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
