# Generated by Django 5.0.2 on 2024-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('nodesAndLinks', models.JSONField(default=dict)),
            ],
        ),
    ]
