# Generated by Django 5.0.2 on 2024-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ideation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='ideations',
            field=models.ManyToManyField(blank=True, related_name='ideation', to='base.ideation'),
        ),
    ]
