# Generated by Django 5.0.2 on 2024-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
